//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaravelAdminMysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public long id { get; set; }
        public long type_id { get; set; }
        public string value { get; set; }
        public long user_id { get; set; }
    
        public virtual contact_types contact_types { get; set; }
        public virtual user user { get; set; }
    }
}
