//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaravelAdminMysql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sql3238345Entities : DbContext
    {
        public sql3238345Entities()
            : base("name=sql3238345Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact_types> contact_types { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<migration> migrations { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<project_technology> project_technology { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<task_comment> task_comment { get; set; }
        public virtual DbSet<task_file> task_file { get; set; }
        public virtual DbSet<task_technology> task_technology { get; set; }
        public virtual DbSet<task_user> task_user { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<technology> technologies { get; set; }
        public virtual DbSet<user_comment> user_comment { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<password_resets> password_resets { get; set; }
    }
}
